### Ping the authentication service
GET {{host}}/auth/ping

### Register a new user
POST {{host}}/auth/register
Content-Type: application/json

{
  "username": "nahid",
  "first_name": "Nazmul",
  "last_name": "Hassan",
  "email": "NHassan96@outlook.com",
  "password": "rootadmin"
}

### Authenticate a user
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "nahid",
  "password": "rootadmin"
}

### Logout a user
POST {{host}}/auth/logout
Authorization: Bearer


### Get user profile
GET {{host}}/auth/profile
Authorization: Bearer


### Update user Password
POST {{host}}/auth/change-password
Authorization: Bearer
Content-Type: application/json

{
  "old_password": "rootadmin",
  "new_password": "newrootadmin"
}


### Update user profile
PUT {{host}}/auth/update-profile
Authorization: Bearer
Content-Type: application/json

{
  "first_name": "Nazmul",
  "email": "NHassan@outlook.com"
}